name: php-dev
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Composer Dependencies
        working-directory: ./app
        run: composer install --prefer-dist
      - name: Run Tests
        working-directory: ./app
        run: composer run-phpunit
      - run: docker build --target app_dev -t hamnavoesolutions/php-dev:1.0 -f ./php/Dockerfile .
      - run: docker build -t hamnavoesolutions/nginx-php:1.0 -f ./nginx/Dockerfile .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push hamnavoesolutions/php-dev:1.1
      - run: docker push hamnavoesolutions/nginx-php:1.0